(set-register ?n '(file . "/home/mortenlp/Dokumenter/Org/Notes.org"))
(set-register ?c '(file . "/home/mortenlp/Dokumenter/Org/contacts.org"))
(set-register ?a '(file . "/home/mortenlp/Dokumenter/Org/archive.org"))
(set-register ?e '(file . "/home/mortenlp/Dokumenter/dotFiles/emacs.d/"))
(set-register ?t '(file . "/home/mortenlp/Dokumenter/test_env/test.sas"))
