(set-register ?n '(file . "/home/mortenlp/Dokumenter/OrgMode/Notes.org"))
(set-register ?c '(file . "/home/mortenlp/Dokumenter/OrgMode/contacts.org"))
(set-register ?a '(file . "/home/mortenlp/Dokumenter/OrgMode/archive.org"))
(set-register ?o '(file . "/home/mortenlp/Dokumenter/CV_og_ansøgning/Ansøgninger/oversigt.org"))
(set-register ?e '(file . "/home/mortenlp/Dokumenter/dotFiles/emacs.d/"))